package com.sawitku.model;

public enum AuditAction {
    AUTH_LOGIN_SUCCESS, AUTH_LOGIN_FAILED, AUTH_REGISTER, AUTH_LOGOUT,
    AUTH_FORGOT_PASSWORD, AUTH_RESET_PASSWORD,
    LAHAN_CREATE, LAHAN_UPDATE, LAHAN_DELETE,
    PANEN_CREATE, PANEN_UPDATE, PANEN_DELETE,
    BIAYA_CREATE, BIAYA_UPDATE, BIAYA_DELETE,
    DIAGNOSA_CREATE, DIAGNOSA_DELETE,
    PAYMENT_CREATE, PAYMENT_STATUS_CHANGE,
    PROFILE_UPDATE, PROFILE_PASSWORD_CHANGE, PROFILE_DELETE_ACCOUNT,
    FEEDBACK_SUBMIT
}
